version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:4.0.3
    environment:
            _R_CHECK_FORCE_SUGGESTS_: false
            _GITHUB_PAT_: 53b5dde802369272464ca0a8447e1c619f80b2db
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: |
            Rscript \
              -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
              -e 'devtools::install_github("jokergoo/ComplexHeatmap")'
              -e 'devtools::install_deps(dependencies = TRUE)'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz
      - store_test_results:
          path: tmp/tests
