version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:4.0.3
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
          environment:
            _R_CHECK_FORCE_SUGGESTS_: false
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - store_test_results:
          path: $CIRCLE_WORKING_DIRECTORY/tests
