# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate column mean and variance, optionally taking a subset of rows to operate on
#'
#' @param sY sparse matrix Gene by cell matrix of counts
#' @param rowSel numeric The selected rows (genes)
#' @param ncores numeric The number of cores
#' @export
colMeanVars <- function(sY, rowSel, ncores = 1L) {
    .Call('_scITD_colMeanVars', PACKAGE = 'scITD', sY, rowSel, ncores)
}

#' calculates factor-stratified means for each column
#'
#' @param sY sparse matrix Gene by cell matrix of counts
#' @param rowSel factor The donor that each cell is from
#' @param numCells numeric Total number of cells belonging to each donor
#' @export
get_means <- function(sY, rowSel, numCells) {
    .Call('_scITD_get_means', PACKAGE = 'scITD', sY, rowSel, numCells)
}

#' calculates factor-stratified sums for each column
#'
#' @param sY sparse matrix Gene by cell matrix of counts
#' @param rowSel factor The donor that each cell is from
#' @export
get_sums <- function(sY, rowSel) {
    .Call('_scITD_get_sums', PACKAGE = 'scITD', sY, rowSel)
}

#' calculates factor-stratified means for each column
#'
#' @param sY sparse matrix Gene by cell matrix of counts
#' @param rowSel factor The donor that each cell is from
#' @param numCells numeric Total number of cells belonging to each donor
#' @export
get_vars <- function(sY, rowSel, numCells) {
    .Call('_scITD_get_vars', PACKAGE = 'scITD', sY, rowSel, numCells)
}

